services:
  app_pino:
    build: .
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db_pino
      - DB_PORT=3306
      - DB_DATABASE=parkir
      - DB_USERNAME=root
      - DB_PASSWORD=123
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=file
      - CACHE_STORE=file
    depends_on:
      - db
  
  web_pino:
    image: nginx:alpine
    ports:
      - "4000-4002:80"
    volumes:
      - .:/var/www/html
      - ./nginx-container.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db_pino
      - app_pino

  db_pino:
    image: mariadb:10.11
    container_name: parking_db
    environment:
      - MYSQL_DATABASE=parkir
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: